return {

	{ -- Linting
		"mfussenegger/nvim-lint",
		event = { "BufReadPre", "BufNewFile" },
		config = function()
			local lint = require("lint")

			-- Configure linters by filetype
			-- NOTE: Linters are provided by Nix, not Mason
			lint.linters_by_ft = {
				-- Web Development
				javascript = { "eslint_d" },
				typescript = { "eslint_d" },
				javascriptreact = { "eslint_d" },
				typescriptreact = { "eslint_d" },

				-- Backend Languages
				go = { "golangcilint" },
				lua = { "selene" },

				-- Infrastructure/Config
				yaml = { "yamllint" },
				terraform = { "tflint" },
				dockerfile = { "hadolint" },
			}

			-- Merge in custom linters declared via home-manager (see
			-- neovim_evan_custom.lua, generated by the home-manager module).
			local ok, custom = pcall(require, "neovim_evan_custom")
			if ok and type(custom) == "table" then
				lint.linters_by_ft = vim.tbl_extend("force", lint.linters_by_ft, custom.linters_by_ft or {})
				for name, def in pairs(custom.linter_defs or {}) do
					lint.linters[name] = vim.tbl_extend("force", lint.linters[name] or {}, def)
				end
			end

			-- Create autocommand which carries out the actual linting
			-- on the specified events.
			local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })
			vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
				group = lint_augroup,
				callback = function()
					-- Only run the linter in buffers that you can modify in order to
					-- avoid superfluous noise, notably within the handy LSP pop-ups that
					-- describe the hovered symbol using Markdown.
					if vim.bo.modifiable then
						lint.try_lint()
					end
				end,
			})
		end,
	},
}
